version: '3.8'

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.frontend
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - DATABASE_URL=postgresql://admin:admin123@database:5432/investments
  #   networks:
  #     - app-network
  #   depends_on:
  #     - database

  database:
    build:
      context: .
      dockerfile: docker/Dockerfile.database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=investments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

